#!/usr/bin/env python3
"""
GitHub Integration Demo for Polymarket Agents

Demonstrates how to use GitHub functionality with your trading agents
for automated reporting, issue tracking, and repository management.
"""

import sys
import os
from typing import Dict, Any

# Add project root to path
sys.path.append(str(Path(__file__).parents[1] / "src"))

from polymarket_agents.subagents.github_agent import (
    check_github_repo_status,
    search_github_issues,
    analyze_github_activity,
    create_market_analysis_report
)
from market_analysis_workflow import MarketAnalyzer


def demonstrate_github_tools():
    """Demonstrate GitHub subagent tools."""
    print("🔧 GitHub Integration Demo")
    print("=" * 50)

    # 1. Check repository status
    print("\\n1. 📊 Repository Status Check")
    print("-" * 30)

    status = check_github_repo_status()
    if "error" in status:
        print(f"❌ {status['error']}")
        print("💡 Make sure your GitHub App credentials are configured in .env")
        return

    print(f"✅ Repository: {status['repository']}")
    print(f"   Owner: {status['owner']}")
    print(f"   Stars: {status['stars']}, Forks: {status['forks']}")
    print(f"   Language: {status['language']}")
    print(f"   Open Issues: {status['open_issues']}")

    # 2. Search for issues
    print("\\n2. 🔍 Issue Search")
    print("-" * 30)

    issues = search_github_issues("trading OR market OR analysis", limit=3)
    if "error" in issues:
        print(f"❌ {issues['error']}")
    else:
        print(f"📋 Found {issues['total_results']} matching issues")
        print(f"   Showing {len(issues['issues'])} results:")

        for issue in issues['issues'][:3]:
            print(f"   • #{issue['number']}: {issue['title'][:50]}...")
            print(f"     Status: {issue['state']}, Author: {issue['author']}")

    # 3. Analyze repository activity
    print("\\n3. 📈 Activity Analysis")
    print("-" * 30)

    activity = analyze_github_activity(days_back=30)
    if "error" in activity:
        print(f"❌ {activity['error']}")
    else:
        print(f"📊 Repository Activity (last 30 days):")
        print(f"   Commits: {activity['activity_metrics']['commits']}")
        print(f"   Issues: {activity['activity_metrics']['issues_created']}")
        print(f"   PRs: {activity['activity_metrics']['pull_requests']}")
        print(f"   Activity Level: {activity['activity_metrics']['activity_level']}")

        if activity['contributors']['unique_contributors'] > 0:
            print(f"   Contributors: {activity['contributors']['unique_contributors']}")
            print(f"   Top Contributor: {activity['contributors']['top_contributors'][0][0]} ({activity['contributors']['top_contributors'][0][1]} commits)")


def demonstrate_automated_reporting():
    """Demonstrate automated market analysis reporting to GitHub."""
    print("\\n4. 🤖 Automated Market Analysis Reporting")
    print("-" * 30)

    # Get a real market analysis
    analyzer = MarketAnalyzer()
    market = "Russia x Ukraine ceasefire in 2025?"
    print(f"🔍 Analyzing: {market}")

    analysis = analyzer.analyze_market_opportunity(market)

    if 'error' in analysis:
        print(f"❌ Analysis failed: {analysis['error']}")
        return

    print("✅ Analysis complete")
    print(f"   Action: {analysis.get('action', 'UNKNOWN')}")
    print(f"   Edge: {analysis.get('edge', 0):.2f}%")

    # Show what the GitHub report would look like
    print("\\n📋 GitHub Issue Preview:")
    print("-" * 30)
    print(f"Title: 📊 Market Analysis: {market}")
    print()
    print("Body:")
    print(f"## Market Analysis Report")
    print(f"**Market:** {market}")
    print(f"**Action:** {analysis.get('action', 'UNKNOWN')}")
    print(f"**Edge:** {analysis.get('edge', 0):.2f}%")
    print()
    print("*Generated by Polymarket Trading Agent*")

    # Uncomment to actually create the issue
    print("\\n💡 To actually create this GitHub issue, run:")
    print("   result = create_market_analysis_report(market, analysis)")
    print("   print(f\"Created issue #{result['issue_number']}\")")


def demonstrate_subagent_integration():
    """Show how GitHub subagent integrates with the full system."""
    print("\\n5. 🔗 Subagent Integration")
    print("-" * 30)

    from polymarket_agents.subagents import create_github_subagent, get_all_subagents

    # Create GitHub subagent
    github_subagent = create_github_subagent()
    print("🤖 GitHub Subagent Created:")
    print(f"   Name: {github_subagent['name']}")
    print(f"   Tools: {len(github_subagent['tools'])}")
    print(f"   Model: {github_subagent.get('model', 'default')}")

    # Show how it fits into the full subagent system
    all_subagents = get_all_subagents()
    print(f"\\n📋 Full Subagent System: {len(all_subagents)} subagents")

    for subagent in all_subagents:
        prefix = "⭐" if subagent['name'] == 'github-agent' else "  "
        print(f"{prefix} {subagent['name']}: {subagent['description'][:60]}...")

    print("\\n🎯 Subagent Use Cases:")
    print("• Main Agent: 'Create a GitHub issue with the latest market analysis'")
    print("• GitHub Subagent: Handles the actual issue creation and formatting")
    print("• Result: Clean main context + properly formatted GitHub issue")


def show_integration_workflow():
    """Show a complete workflow example."""
    print("\\n6. 🚀 Complete Integration Workflow")
    print("-" * 30)

    workflow = [
        {
            "step": "Market Analysis",
            "agent": "Trading Agent",
            "action": "Analyze multiple markets for opportunities",
            "output": "Structured analysis results"
        },
        {
            "step": "Report Generation",
            "agent": "GitHub Subagent",
            "action": "Format analysis as GitHub issue with proper labels",
            "output": "Well-formatted issue ready for creation"
        },
        {
            "step": "Issue Creation",
            "agent": "GitHub Subagent",
            "action": "Create issue in repository with analysis details",
            "output": "GitHub issue URL and tracking number"
        },
        {
            "step": "Progress Tracking",
            "agent": "GitHub Subagent",
            "action": "Monitor issue status and updates",
            "output": "Status updates and notifications"
        }
    ]

    print("📋 Automated Trading Analysis → GitHub Reporting:")
    print()

    for i, step in enumerate(workflow, 1):
        print(f"{i}. {step['step']}")
        print(f"   🤖 {step['agent']}")
        print(f"   🎯 {step['action']}")
        print(f"   📤 {step['output']}")
        print()

    print("✨ Benefits:")
    print("• 📊 Automated documentation of trading decisions")
    print("• 📋 Structured tracking of market analysis")
    print("• 🤝 Team collaboration on trading insights")
    print("• 📈 Performance tracking and audit trail")


def main():
    """Main demonstration."""
    try:
        demonstrate_github_tools()
        demonstrate_automated_reporting()
        demonstrate_subagent_integration()
        show_integration_workflow()

        print("\\n🎉 GitHub Integration Complete!")
        print("\\n📚 Next Steps:")
        print("1. Set up your GitHub App credentials in .env")
        print("2. Install pygithub: pip install pygithub langchain-community")
        print("3. Test the GitHub subagent with your trading workflows")
        print("4. Set up automated reporting for your trading decisions")

    except Exception as e:
        print(f"\\n❌ Demo failed: {e}")
        print("\\n💡 Make sure your .env file has GitHub credentials:")
        print("   GITHUB_APP_ID=your_app_id")
        print("   GITHUB_APP_PRIVATE_KEY=/path/to/private_key.pem")
        print("   GITHUB_REPOSITORY=username/repo-name")


if __name__ == "__main__":
    main()
